config/routes.rb
Niche::Application.routes.draw do
  get "edit_users" => "users#edit", :as => "edit_users"
  get "list_users" => "users#index", :as => "list_users"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "contact_me" => "messages#new", :as => "contact_me"
  root :to => "home#index"

  resources :users
  resources :sessions
  resources :messages

end

app/models/message.rb
class Message
  # To change this template use File | Settings | File Templates.
  include ActiveAttr::Model

  attribute :name
  attribute :email
  attribute :phone
  attribute :contact_method
  attribute :type
  attribute :content

  validates_presence_of :name
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_length_of :content, :maximum => 50
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :fname, :lname, :password, :password_confirmation, :role, :username

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username, :on => :create
  validates_presence_of :email
  validates_presence_of :lname
  validates_presence_of :fname
  validates_presence_of :role
  validates_uniqueness_of :email
  validates_uniqueness_of :username

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # To change this template use File | Settings | File Templates.
  def index
    render :layout => 'application_index'
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      # TODO send message here
      UserMailer.message_confirmation(@message).deliver
      redirect_to root_url, notice: "Message sent! Thank you!"
    else
      render "new"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      #change after log in page here
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  #PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to list_users_url, notice: 'User was successfully updated!' }
    else
        format.html { render action: "edit" }

      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
  <div class="slider_float">
    <div id="slider">


      <div><img src="/assets/kitty.jpg" width="600" height="383" alt="photo1 title"/></div>

      <div><img src="/assets/kitty4.jpg" width="600" height="450" alt="photo2 title"/></div>

      <div><img src="/assets/kitty3.jpg" width="600" height="800" alt="photo3 title"/></div>

      <div><img src="/assets/kitty2.jpg" width="600" height="800" alt="photo4 title"/></div>


    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photography Niche</title>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "navigation", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>

  <!--navigation and slideshow-->
  <script>
      $.noConflict();
      jQuery(document).ready(function () {
          $("#navigation > li > a").click(function (e) { // binding onclick
              if ($(this).parent().hasClass('selected')) {
                  $("#navigation .selected div div").fadeOut(); // hiding popups
                  $("#navigation .selected").removeClass("selected");
              } else {
                  $("#navigation .selected div div").fadeOut(); // hiding popups
                  $("#navigation .selected").removeClass("selected");

                  if ($(this).next(".subs").length) {
                      $(this).parent().addClass("selected"); // display popup
                      $(this).next(".subs").children().slideDown(1000, function(){});
                  }
              }
              e.stopPropagation();
              e.preventDefault();
          });

          $("html").click(function () { // binding onclick to body
              $("#navigation .selected div div").fadeOut(); // hiding popups
              $("#navigation .selected").removeClass("selected");

          });

      });

  </script>

</head>

<body>

<div class="page">
  <div class="side_header">
    <h1>Photography Niche</h1>
    <p>by Nichelle Bailey</p>
    <a href="<%= root_url %>">Home</a>
  </div>

  <ul id="navigation">

    <li>
      <a href="#">Portfolio</a>
      <div class="subs">
        <div>
          <ul>
            <li><a href="#" class="clicker">Milestones</a></li>
            <li><a href="#" class="clicker">Portraits</a></li>
            <li><a href="#" class="clicker">Together</a></li>
            <li><a href="#" class="clicker">Little Ones</a></li>
            <li><a href="#" class="clicker">Beginnings</a></li>
            <li><a href="#" class="clicker">Expecting</a></li>
          </ul>
        </div>
      </div>
      <div class="clear"></div>
    </li>

    <li>
      <a href="#">Weddings and Engagements</a>
      <div class="subs">
        <div>
          <ul>
            <li><a href="#">Celebrate</a></li>
            <li><a href="#">I Do</a></li>
            <li><a href="#">Anticipation</a></li>
            <li><a href="#">Engagements</a></li>
          </ul>
        </div>
      </div>
      <div class="clear"></div>
    </li>

    <li>
      <a href="#">Information</a>
      <div class="subs">
        <div>
          <ul>
            <li><a href="#">Investment</a></li>
            <li><a href="#">Offerings</a></li>
            <li><a href="#">The Artist</a></li>
          </ul>
        </div>
      </div>
      <div class="clear"></div>
    </li>

    <div class="no_drop_down">
      <% if current_user && current_user.role == "1" %>
          <div class=logged_in_message>
            <li>Logged in as <%= current_user.username %>.</li>
            <li><%= link_to "Register People", sign_up_path %></li>
            <li><%= link_to "List of Clients", list_users_path%></li>
            <li><%= link_to "Log out", log_out_path %></li>
          </div>
      <% elsif current_user && current_user.role == "2" %>
          <li><%= link_to "Contact Me", contact_me_path %></li>
          <li><%= link_to "Log out", log_out_path %></li>
          <div class="logged_in_message">
            Logged in as <%= current_user.username %>.
          </div>
      <% else %>
          <li><%= link_to "Contact Me", contact_me_path %></li>
          <li><%= link_to "Events", log_in_path %></li>
      <% end %>

    </div>

    <div class="clear"></div>

  </ul>
  <div class="logged_in_message">
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </div>



  </ul>


    <%= yield %>


</div>



</body>
</html>

app/views/layouts/application_index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photography Niche</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

  <%= javascript_include_tag "jquery.easing.1.2" %>
  <%= javascript_include_tag "swfobject" %>
  <%= stylesheet_link_tag    "anythingslider", :media => "all" %>
  <%= javascript_include_tag "jquery.anythingslider" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= stylesheet_link_tag    "navigation", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>

  <!--Slide show-->
  <script>
      $.noConflict();
      jQuery(document).ready(function () {
          $("#navigation > li > a").click(function (e) { // binding onclick
                  if ($(this).parent().hasClass('selected')) {
                    $("#navigation .selected div div").fadeOut(); // hiding popups
                    $("#navigation .selected").removeClass("selected");
                  } else {
                    $("#navigation .selected div div").fadeOut(); // hiding popups
                    $("#navigation .selected").removeClass("selected");

                    if ($(this).next(".subs").length) {
                      $(this).parent().addClass("selected"); // display popup
                      $(this).next(".subs").children().slideDown(1000, function(){});
                    }
                  }
                  e.stopPropagation();
                  e.preventDefault();
          });

          $("html").click(function () { // binding onclick to body
             $("#navigation .selected div div").fadeOut(); // hiding popups
             $("#navigation .selected").removeClass("selected");

          });

          $('#slider').anythingSlider({
                  autoPlay:true,
                  resizeContents:false,
                  buildStartStop:false,
                  buildNavigation:false,
                  easing:"swing"

      });
      });

  </script>

</head>

<body>

<div class="page">
    <div class="side_header">
      <h1>Photography Niche</h1>
      <p>by Nichelle Bailey</p>
      <a href="<%= root_url %>">Home</a>
    </div>

      <ul id="navigation">

          <li>
            <a href="#">Portfolio</a>
             <div class="subs">
               <div>
                 <ul>
                    <li><a href="#" class="clicker">Milestones</a></li>
                    <li><a href="#" class="clicker">Portraits</a></li>
                    <li><a href="#" class="clicker">Together</a></li>
                    <li><a href="#" class="clicker">Little Ones</a></li>
                    <li><a href="#" class="clicker">Beginnings</a></li>
                    <li><a href="#" class="clicker">Expecting</a></li>
                  </ul>
                 </div>
               </div>
            <div class="clear"></div>
          </li>

        <li>
          <a href="#">Weddings and Engagements</a>
            <div class="subs">
              <div>
                  <ul>
                    <li><a href="#">Celebrate</a></li>
                    <li><a href="#">I Do</a></li>
                    <li><a href="#">Anticipation</a></li>
                    <li><a href="#">Engagements</a></li>
                  </ul>
                </div>
              </div>
          <div class="clear"></div>
        </li>

        <li>
          <a href="#">Information</a>
          <div class="subs">
            <div>
              <ul>
                <li><a href="#">Investment</a></li>
                <li><a href="#">Offerings</a></li>
                <li><a href="#">The Artist</a></li>
               </ul>
            </div>
          </div>
          <div class="clear"></div>
        </li>

        <div class="no_drop_down">
        <% if current_user && current_user.role == "1" %>
            <div class=logged_in_message>
                <li>Logged in as <%= current_user.username %>.</li>
                <li><%= link_to "Register People", sign_up_path %></li>
                <li><%= link_to "List of Clients", list_users_path%></li>
                <li><%= link_to "Log out", log_out_path %></li>
            </div>
        <% elsif current_user && current_user.role == "2" %>
            <li><%= link_to "Contact Me", contact_me_path %></li>
            <li><%= link_to "Log out", log_out_path %></li>
                <div class="logged_in_message">
                    Logged in as <%= current_user.username %>.
                </div>
        <% else %>
            <li><%= link_to "Contact Me", contact_me_path %></li>
            <li><%= link_to "Events", log_in_path %></li>
        <% end %>

        </div>

      <div class="clear"></div>

    </ul>
    <div class="logged_in_message">
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    </div>

  <%= yield %>

</div>



</body>
</html>

app/views/layouts/application_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthTest</title>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <%= javascript_include_tag "MenuMatic_0.68.3" %>


  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= stylesheet_link_tag    "MenuMatic", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>


  <script>
      $(document).ready(function(){
          $('#myMenuButton').menu({
              content: $('#myContent').html(),
              maxHeight: 180,
              positionOpts: { offsetX: 10, offsetY: 20 },
              showSpeed: 300
          });
      });
  </script>

</head>

<body>
<div class="page">
  <div class="side_header">
    <h1>Photography Niche</h1>
    <p>by Nichelle Bailey</p>
  </div>

  <div id="nav">
    <ul>
      <li>
        <a href="#" class="clicker">Portfolio</a>
        <ul>
          <li><a href="#">Milestones</a></li>
          <li><a href="#">Portraits</a></li>
          <li><a href="#">Together</a></li>
          <li><a href="#">Little Ones</a></li>
          <li><a href="#">Beginnings</a></li>
          <li><a href="#">Expecting</a></li>
        </ul>
      </li>
      </li>

      <li>
        <a href="#" class="clicker">Weddings and Engagements</a>
        <ul>
          <li><a href="#">Celebrate</a></li>
          <li><a href="#">I Do</a></li>
          <li><a href="#">Anticipation</a></li>
          <li><a href="#">Engagements</a></li>
        </ul>
      </li>

      <li>
        <a href="#" class="clicker">Information</a>
        <ul>
          <li><a href="#">Investment</a></li>
          <li><a href="#">Offerings</a></li>
          <li><a href="#">The Artist</a></li>
        </ul>
      </li>

      <% if current_user && current_user.role == "1" %>
          <li><%= link_to "Register People", sign_up_path %></li>
          <li><%= link_to "List of Users", list_users_path%></li>
          <li><%= link_to "Log out", log_out_path %></li>
      <% elsif current_user && current_user.role == "2" %>
          Logged in as <%= current_user.username %>.
          <li><%= link_to "Contact Me", contact_me_path %></li>
          <li><%= link_to "Log out", log_out_path %></li>
      <% else %>
          <li><%= link_to "Contact Me", contact_me_path %></li>
          <li><%= link_to "Events", log_in_path %></li>
      <% end %>

    </ul>

    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </div>



  <%= yield %>



</div>


</body>
</html>

app/views/layouts/application_plain.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthTest</title>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

  <%= javascript_include_tag "unslider.min" %>
  <%= javascript_include_tag "application" %>

  <%= stylesheet_link_tag "banner", :media => "all" %>

  <%= csrf_meta_tags %>

  <script>

      $.noConflict();
      jQuery(document).ready(function () {
          $('.banner').unslider({});
      });

  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/new.html.erb
<script text="text/javascript">
    $j('input[id="message_phone"]').each (function(){
                $j(this).mask("(999) 999-9999");
            }
    );
</script>

<div class="contact">
    <h1>Contact Me</h1>

    <%= form_for @message do |f| %>
        <% if @message.errors.any? %>
            <div class="error_messages">
              <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
              <ul>
                <% @message.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>

        <div class="field">
        <div id="phone">
          <%= f.label :phone %>
          <%= f.text_field :phone %>
        </div>
          </div>

        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>

        Preferred Method of Contact
        <div class="field">
          <%= f.label :Email %>
          <%= f.radio_button :contact_method, 'Email' %>

          <%= f.label :Phone %>
          <%= f.radio_button :contact_method, 'Phone' %>
        </div>

        <div class="field">
        Type of Photo Session
        <%= f.select :type, [['Wedding', 'Wedding'], ['Engagement', 'Engagement'], ['Baby', 'Baby'], ['Senior', 'Senior'], ['Family', 'Family'], ['Other', 'Other']] %>
        </div>

        <div class="field">
          <%= f.label :content, "Message(Optional)" %><br />
          <%= f.text_area :content %>
        </div>
        <div class="actions"><%= f.submit "Send Message" %></div>
    <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :First_Name %><br />
      <%= f.text_field :fname %>
    </p>
    <p>
      <%= f.label :Last_Name %><br />
      <%= f.text_field :lname %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p>
      <%= f.label :role %><br />
      <%= f.text_field :role %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/edit.html.erb
<div class="new_client">
<h1>Edit Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="client_listing">
<h1>Client Listing</h1>

<table>
  <tr>
    <th>Last name</th>
    <th>First name</th>
    <th>Email</th>
    <th>Username</th>
    <th>Password</th>
    <th>Access level</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.lname %></td>
        <td><%= user.fname %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />
</div>

app/views/users/new.html.erb
<div class="new_client">
<h1>Register a New Client</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :First_Name %>
      <%= f.text_field :fname %>
    </p>
    <p>
      <%= f.label :Last_Name %>
      <%= f.text_field :lname %>
    </p>
    <p>
      <%= f.label :Email %>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :Username %>
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :Password %>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :Password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </p>
    <p>
      <%= f.label :role %>
      <%= f.text_field :role %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>
</div>